---
opsman-configuration:
  vsphere:
    vcenter:
      url: vcsa-01.haas-224.pez.pivotal.io
      username: Administrator@vsphere.local
      password: ((vcenter_password))
      datastore: LUN01
      datacenter: Datacenter
      resource_pool: /Datacenter/host/Cluster/Resources/pas-az1
      folder: /Datacenter/vm/
      insecure: 1
    disk_type: thin
    private_ip: 192.168.1.10
    dns: 10.192.2.10
    ntp: time.svc.pivotal.io
    ssh_public_key: ((opsman_ssh_key.public_key))
    hostname: ops-manager.sandbox.haas-224.pez.pivotal.io
    network: PAS-Infrastructure
    netmask: 255.255.255.0
    gateway: 192.168.1.1
    vm_name: pas-sandbox-om
    memory: 8
    cpu: 1
